### PR TITLE
Refactored. Now to work on the form.

### PR DESCRIPTION
**Pull request by uxFeranmi**

### CODE REVIEW

**Comment by uxFeranmi** [comment]
Styles for shared components now live in the php file. This makes components more self contained and reduces load time.

**Comment by uxFeranmi** [comment]
So how do we split this?

**Comment by uxFeranmi** [comment]
You know what? Start with the success page. Include the shared titlebar there.

**Comment by uxFeranmi** [comment]
Then the background graphics were uploaded on slack. Please add them to both pages.

**Comment by cirqlar** [comment]
Alright. I'll see what I can do.

**Review by cirqlar — APPROVED** [review]

**Comment by uxFeranmi** [comment]
I'll continue with the form. Let's keep each other posted.

**Comment by uxFeranmi** [comment]
Merci.

**Pull request merged**
